In [1]:
import pickle
import pathlib
import numpy as np

In [2]:
DATA_DIR = pathlib.Path.cwd().parent / 'data'
RAW_DATA_DIR = DATA_DIR / 'raw'
PDF_DIR = RAW_DATA_DIR / 'pdf'
DF_DIR = RAW_DATA_DIR / 'dataframe'

In [3]:
with open(DF_DIR / 'data.pkl', 'rb') as f:
    raw_data = pickle.load(f)

In [4]:
raw_data.keys()

dict_keys(['2021-12', '2022-01', '2022-02', '2022-03', '2022-04', '2022-05', '2022-06', '2022-07', '2022-08', '2022-10', '2022-11', '2022-12', '2023-01', '2023-03', '2023-04', '2023-05', '2023-06', '2023-07', '2023-08', '2023-09', '2023-10', '2023-11', '2023-12', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2022-09', '2023-02'])

In [5]:
data = raw_data.copy()
example = data['2021-12']
example

,company,ticker,industry,portfolio_weight,reccomendation,price,target,upside,market_cap
0,Arezzo,ARZZ3,Varejo,10%,Compra,"R$ 68,20","R$ 108,00",58%,"R$ 6,8"
1,Assaí,ASAI3,Varejo,10%,Compra,"R$ 13,05","R$ 23,00",76%,"R$ 17,6"
2,Banco do Brasil,BBAS3,Bancos,10%,Compra,"R$ 30,81","R$ 52,00",69%,"R$ 87,9"
3,Gerdau,GGBR4,Mineração e Siderurgia,10%,Compra,"R$ 25,80","R$ 32,00",24%,"R$ 44,0"
4,Localiza,RENT3,Transportes,10%,Compra,"R$ 52,25","R$ 68,00",30%,"R$ 39,6"
5,RaiaDrogasil,RADL3,Varejo,10%,Compra,"R$ 22,61","R$ 27,00",19%,"R$ 37,4"
6,Rumo,RAIL3,Transportes,10%,Compra,"R$ 17,62","R$ 24,00",36%,"R$ 32,7"
7,São Martinho,SMTO3,"Agro, Alimentos e Bebidas",10%,Compra,"R$ 36,72","R$ 38,00",3%,"R$ 12,7"
8,Vale,VALE3,Mineração e Siderurgia,10%,Compra,"R$ 69,50","R$ 122,00",76%,"R$ 63,5"
9,Weg,WEGE3,Bens de Capital,10%,Compra,"R$ 32,41","R$ 50,00",54%,"R$ 136,0"

In [6]:
# Delete unused columns
unused_columns = ['company', 'industry', 'upside', 'market_cap']
for key in data.keys():
    data[key].drop(columns=unused_columns, inplace=True)

In [7]:
example

  ticker portfolio_weight reccomendation     price     target
0  ARZZ3              10%         Compra  R$ 68,20  R$ 108,00
1  ASAI3              10%         Compra  R$ 13,05   R$ 23,00
2  BBAS3              10%         Compra  R$ 30,81   R$ 52,00
3  GGBR4              10%         Compra  R$ 25,80   R$ 32,00
4  RENT3              10%         Compra  R$ 52,25   R$ 68,00
5  RADL3              10%         Compra  R$ 22,61   R$ 27,00
6  RAIL3              10%         Compra  R$ 17,62   R$ 24,00
7  SMTO3              10%         Compra  R$ 36,72   R$ 38,00
8  VALE3              10%         Compra  R$ 69,50  R$ 122,00
9  WEGE3              10%         Compra  R$ 32,41   R$ 50,00

In [8]:
for df in data.values():
    for column in ['price', 'target']:
        df[column] = df[column].apply(lambda x: x.replace('R$', '').replace(',', '.'))
        df[column] = df[column].apply(lambda x: np.nan if x == '-' or x == 'Restrito' else x)
        df[column] = df[column].astype(float)

In [9]:
for df in data.values():
    df['portfolio_weight'] = df['portfolio_weight'].apply(lambda x: x.replace('%', '').replace(',', '.'))
    df['portfolio_weight'] = df['portfolio_weight'].astype(float)
    df['portfolio_weight'] = df['portfolio_weight'] / 100

In [10]:
example

  ticker  portfolio_weight reccomendation  price  target
0  ARZZ3               0.1         Compra  68.20   108.0
1  ASAI3               0.1         Compra  13.05    23.0
2  BBAS3               0.1         Compra  30.81    52.0
3  GGBR4               0.1         Compra  25.80    32.0
4  RENT3               0.1         Compra  52.25    68.0
5  RADL3               0.1         Compra  22.61    27.0
6  RAIL3               0.1         Compra  17.62    24.0
7  SMTO3               0.1         Compra  36.72    38.0
8  VALE3               0.1         Compra  69.50   122.0
9  WEGE3               0.1         Compra  32.41    50.0

In [11]:
for df in data.values():
    df['ticker'] = df['ticker'].apply(lambda x: x + '.SA')
    df['ticker'] = df['ticker'].astype(str)